// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8MFXua4Z0XXAMBWxEjpnAKi1rIjtmoyI',
    appId: '1:999633053304:android:0531e50028ca68447aef8d',
    messagingSenderId: '999633053304',
    projectId: 'idoc-7351a',
    storageBucket: 'idoc-7351a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrXMUtFUGgQrCX2Lqcif6fM2O89PtA8Uw',
    appId: '1:999633053304:ios:70b3c45673cac3bf7aef8d',
    messagingSenderId: '999633053304',
    projectId: 'idoc-7351a',
    storageBucket: 'idoc-7351a.appspot.com',
    androidClientId: '999633053304-39co13lr02va9to1gdc347u2jokbgn1o.apps.googleusercontent.com',
    iosClientId: '999633053304-p5ehv8sh3ohep3qpvog10k7ovtc5fuv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.testklk',
  );
}
